# Generated by Django 4.2.20 on 2025-04-03 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("zgw_consumers", "0022_set_default_service_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "open_product_api_service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="open_product_api_service",
                        to="zgw_consumers.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Open Product API client configuration",
            },
        ),
    ]
