# Generated by Django 4.2.20 on 2025-04-03 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_consumers", "0022_set_default_service_slug"),
        ("openproductapiclient", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="open_product_types_api_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="open_product_types_api_service",
                to="zgw_consumers.service",
            ),
        ),
    ]
